name: build every tag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          path: target/release/sentrum.exe
          name: sentrum.exe
      - if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          path: target/release/sentrum*
          name: sentrum_linux
      - if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          path: target/release/sentrum*
          name: sentrum_macos
